# Generated by Django 2.1.4 on 2019-05-21 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0003_auto_20190521_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dialogue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='private_chat.Dialogue'),
            preserve_default=False,
        ),
    ]
