# Generated by Django 2.1.4 on 2019-05-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0004_message_dialogue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='dialogue',
            new_name='chat',
        ),
    ]
