# Generated by Django 2.1.4 on 2019-05-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0005_auto_20190521_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='dialogue',
        ),
    ]
